server:
  port: 8100

# 整合 feign, hystrix
feign:
  hystrix:
    enabled: true

# actuator
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"